def printy():
    print("bootSavePlayer1")
    print(bootSavePlayer1)
    print("bootSavePlayer2")
    print(bootSavePlayer2)

    print("boot2Save1Player1")  
    print(boot2Save1Player1)
    print("boot2Save2Player1")
    print(boot2Save2Player1)
    print("boot2Save3Player1")
    print(boot2Save3Player1)
    print("boot2Save4Player1")
    print(boot2Save4Player1)

    print("boot2Save1Player2")
    print(boot2Save1Player2)
    print("boot2Save2Player2")
    print(boot2Save2Player2)
    print("boot2Save3Player2")
    print(boot2Save3Player2)
    print("boot2Save4Player2")
    print(boot2Save4Player2)